<?php

namespace Database\Seeders;

use App\Models\MasterData\Plant;
use App\Models\MasterData\PlantCategory;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class PlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $plantCategories = [
            [
                'name' => 'Tanaman Pangan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tanaman Perkebunan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tanaman Hutan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tanaman Hias',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Tanaman Obat',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        PlantCategory::insert($plantCategories);

        $plantCategories = PlantCategory::all();

        $tanamanPanganCategory = $plantCategories->where('name', 'Tanaman Pangan')->first()->id;
        $tanamanPerkebunanCategory = $plantCategories->where('name', 'Tanaman Perkebunan')->first()->id;
        $tanamanHutanCategory = $plantCategories->where('name', 'Tanaman Hutan')->first()->id;
        $tanamanHiasCategory = $plantCategories->where('name', 'Tanaman Hias')->first()->id;
        $tanamanObatCategory = $plantCategories->where('name', 'Tanaman Obat')->first()->id;

        $plants = [
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Padi',
                'scientific_name' => 'Oryza sativa',
                'habitat' => 'Asia',
                'benefits' => 'Bahan makanan pokok, bahan baku industri',
                'nutritional_value' => 'Karbohidrat, protein, lemak, vitamin, mineral',
                'pests_and_diseases' => 'Wereng, hama batang, hama daun, penyakit blas, penyakit hawar daun',
                'cultivation_techniques' => 'Menanam benih, pemupukan, pengairan, pengendalian hama dan penyakit',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Jagung',
                'scientific_name' => 'Zea mays',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Bahan makanan, pakan ternak, bahan baku industri',
                'nutritional_value' => 'Karbohidrat, serat, vitamin B, asam folat',
                'pests_and_diseases' => 'Ulat bulu, ulat grayak, penyakit bercak daun, penyakit karat',
                'cultivation_techniques' => 'Menanam benih, penanaman jarak, pemupukan, pengairan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPerkebunanCategory,
                'name' => 'Kelapa Sawit',
                'scientific_name' => 'Elaeis guineensis',
                'habitat' => 'Afrika Barat',
                'benefits' => 'Minyak kelapa sawit, bahan baku makanan, bahan baku industri',
                'nutritional_value' => 'Minyak nabati, vitamin E',
                'pests_and_diseases' => 'Penggerek buah, penyakit busuk buah, penyakit layu',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, penyiangan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPerkebunanCategory,
                'name' => 'Karet',
                'scientific_name' => 'Hevea brasiliensis',
                'habitat' => 'Amazon',
                'benefits' => 'Karet alam, bahan baku industri karet',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Kutu karet, penyakit bercak karet, penyakit layu',
                'cultivation_techniques' => 'Penanaman bibit, penyadapan getah, pemupukan, pengendalian hama dan penyakit',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPerkebunanCategory,
                'name' => 'Kakao',
                'scientific_name' => 'Theobroma cacao',
                'habitat' => 'Amerika Selatan',
                'benefits' => 'Bubuk kakao, cokelat, bahan baku industri',
                'nutritional_value' => 'Serat, flavonoid, magnesium, zat besi',
                'pests_and_diseases' => 'Kutu daun, hama ulat, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, penyiraman, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPerkebunanCategory,
                'name' => 'Teh',
                'scientific_name' => 'Camellia sinensis',
                'habitat' => 'Asia Timur',
                'benefits' => 'Minuman teh, bahan baku industri',
                'nutritional_value' => 'Antioksidan, kafein',
                'pests_and_diseases' => 'Ulat teh, penyakit kanker daun, penyakit jamur',
                'cultivation_techniques' => 'Penanaman bibit, pemangkasan, penyiraman, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPerkebunanCategory,
                'name' => 'Kopi',
                'scientific_name' => 'Coffea arabica',
                'habitat' => 'Afrika Timur',
                'benefits' => 'Minuman kopi, bahan baku industri',
                'nutritional_value' => 'Kafein, antioksidan',
                'pests_and_diseases' => 'Ulat buah kopi, hama ulat, penyakit karat daun',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, penyiraman, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kacang Tanah',
                'scientific_name' => 'Arachis hypogaea',
                'habitat' => 'Amerika Selatan',
                'benefits' => 'Makanan, minyak kacang tanah, bahan baku industri',
                'nutritional_value' => 'Protein, lemak, serat, vitamin B',
                'pests_and_diseases' => 'Ulat kacang tanah, hama kumbang, penyakit bercak daun',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kedelai',
                'scientific_name' => 'Glycine max',
                'habitat' => 'Asia Timur',
                'benefits' => 'Makanan, susu kedelai, bahan baku industri',
                'nutritional_value' => 'Protein, lemak, serat, vitamin B',
                'pests_and_diseases' => 'Ulat kedelai, hama kumbang, penyakit bercak daun',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Ubi Jalar',
                'scientific_name' => 'Ipomoea batatas',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Makanan, pakan ternak, bahan baku industri',
                'nutritional_value' => 'Karbohidrat, serat, vitamin A, vitamin C',
                'pests_and_diseases' => 'Ulat ubi, hama kumbang, penyakit layu',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Ubi Kayu',
                'scientific_name' => 'Manihot esculenta',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Makanan, bahan baku industri',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Kutu daun, penyakit layu, penyakit akar',
                'cultivation_techniques' => 'Penanaman umbi, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Singkong',
                'scientific_name' => 'Manihot esculenta',
                'habitat' => 'Amerika Selatan',
                'benefits' => 'Makanan, pakan ternak, bahan baku industri',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Kutu daun, penyakit layu, penyakit akar',
                'cultivation_techniques' => 'Penanaman umbi, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kentang',
                'scientific_name' => 'Solanum tuberosum',
                'habitat' => 'Andes, Amerika Selatan',
                'benefits' => 'Makanan, bahan baku industri',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Kutu kentang, penyakit layu, penyakit busuk',
                'cultivation_techniques' => 'Penanaman umbi, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Wortel',
                'scientific_name' => 'Daucus carota',
                'habitat' => 'Eropa dan Asia Barat Daya',
                'benefits' => 'Makanan, sumber vitamin A',
                'nutritional_value' => 'Karbohidrat, serat, vitamin A',
                'pests_and_diseases' => 'Ulat wortel, penyakit bercak daun, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Bawang Putih',
                'scientific_name' => 'Allium sativum',
                'habitat' => 'Asia Tengah',
                'benefits' => 'Bumbu masak, obat tradisional',
                'nutritional_value' => 'Serat, vitamin C, mangan',
                'pests_and_diseases' => 'Kutu bawang, penyakit bercak daun, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman bulb, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Bawang Merah',
                'scientific_name' => 'Allium cepa var. ascalonicum',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Bumbu masak, sumber antioksidan',
                'nutritional_value' => 'Serat, vitamin C, mangan',
                'pests_and_diseases' => 'Kutu bawang, penyakit bercak daun, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman bulb, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Cabai',
                'scientific_name' => 'Capsicum annuum',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Bumbu masak, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, serat',
                'pests_and_diseases' => 'Thrips, penyakit busuk buah, penyakit layu',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Tomat',
                'scientific_name' => 'Solanum lycopersicum',
                'habitat' => 'Amazone',
                'benefits' => 'Sayuran, bahan baku saus, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, likopen',
                'pests_and_diseases' => 'Ulat tomat, penyakit busuk buah, penyakit layu',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Terong',
                'scientific_name' => 'Solanum melongena',
                'habitat' => 'India',
                'benefits' => 'Sayuran, bumbu masak',
                'nutritional_value' => 'Serat, vitamin C, vitamin K',
                'pests_and_diseases' => 'Ulat terong, penyakit busuk buah, penyakit layu',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Melon',
                'scientific_name' => 'Cucumis melo',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, kalium',
                'pests_and_diseases' => 'Kutu daun, penyakit bulai, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Semangka',
                'scientific_name' => 'Citrullus lanatus',
                'habitat' => 'Afrika',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, likopen',
                'pests_and_diseases' => 'Ulat buah, penyakit layu, penyakit bulai',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Jeruk',
                'scientific_name' => 'Citrus sinensis',
                'habitat' => 'Asia Timur',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, serat',
                'pests_and_diseases' => 'Kutu jeruk, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Apel',
                'scientific_name' => 'Malus domestica',
                'habitat' => 'Asia Tengah',
                'benefits' => 'Buah segar, sumber serat',
                'nutritional_value' => 'Serat, vitamin C, vitamin K',
                'pests_and_diseases' => 'Ulat buah apel, penyakit kanker daun, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Pisang',
                'scientific_name' => 'Musa',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber kalium',
                'nutritional_value' => 'Kalium, vitamin C, vitamin B6',
                'pests_and_diseases' => 'Kutu pisang, penyakit sigatoka, penyakit layu',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Mangga',
                'scientific_name' => 'Mangifera indica',
                'habitat' => 'Asia Selatan',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, serat',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Durian',
                'scientific_name' => 'Durio',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber kalium',
                'nutritional_value' => 'Kalium, vitamin C, lemak',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Salak',
                'scientific_name' => 'Salacca zalacca',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber serat',
                'nutritional_value' => 'Serat, vitamin C, vitamin A',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Nangka',
                'scientific_name' => 'Artocarpus heterophyllus',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku masakan',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Rambutan',
                'scientific_name' => 'Nephelium lappaceum',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, serat',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Sagu',
                'scientific_name' => 'Metroxylon sagu',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Sumber karbohidrat',
                'nutritional_value' => 'Karbohidrat',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit daun',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kopasanda',
                'scientific_name' => 'Dioscorea esculenta',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Sumber karbohidrat',
                'nutritional_value' => 'Karbohidrat, serat',
                'pests_and_diseases' => 'Ulat daun, penyakit busuk umbi, penyakit layu',
                'cultivation_techniques' => 'Penanaman umbi, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHutanCategory,
                'name' => 'Bambu',
                'scientific_name' => 'Bambusoideae',
                'habitat' => 'Asia, Amerika, Afrika',
                'benefits' => 'Bahan bangunan, alat rumah tangga',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kumbang, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rumpun, pemangkasan, pengairan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Pisang Raja',
                'scientific_name' => 'Musa acuminata × balbisiana',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber kalium',
                'nutritional_value' => 'Kalium, vitamin C, vitamin B6',
                'pests_and_diseases' => 'Kutu pisang, penyakit sigatoka, penyakit layu',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Manggis',
                'scientific_name' => 'Garcinia mangostana',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber antioksidan',
                'nutritional_value' => 'Vitamin C, serat, xanthone',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Belimbing',
                'scientific_name' => 'Averrhoa carambola',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, serat, asam oksalat',
                'pests_and_diseases' => 'Ulat buah, penyakit layu, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHutanCategory,
                'name' => 'Pinang',
                'scientific_name' => 'Areca catechu',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Biji pinang, bahan baku sirih',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kumbang, penyakit busuk akar, penyakit layu',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kepel',
                'scientific_name' => 'Stelechocarpus burahem',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku jamu',
                'nutritional_value' => 'Vitamin C, serat, alkaloid',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Jambu Biji',
                'scientific_name' => 'Psidium guajava',
                'habitat' => 'Amerika Tropis',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, serat, karotenoid',
                'pests_and_diseases' => 'Ulat daun, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Jambu Air',
                'scientific_name' => 'Syzygium aqueum',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, serat, karotenoid',
                'pests_and_diseases' => 'Ulat daun, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Lengkeng',
                'scientific_name' => 'Dimocarpus longan',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin B, fosfor',
                'pests_and_diseases' => 'Ulat buah, penyakit layu, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Nenas',
                'scientific_name' => 'Ananas comosus',
                'habitat' => 'Amerika Selatan',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, serat, bromelain',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit layu',
                'cultivation_techniques' => 'Penanaman tanaman anakan, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPerkebunanCategory,
                'name' => 'Coklat',
                'scientific_name' => 'Theobroma cacao',
                'habitat' => 'Amerika Selatan',
                'benefits' => 'Bubuk kakao, cokelat, bahan baku industri',
                'nutritional_value' => 'Serat, flavonoid, magnesium, zat besi',
                'pests_and_diseases' => 'Kutu daun, hama ulat, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, penyiraman, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Alpukat',
                'scientific_name' => 'Persea americana',
                'habitat' => 'Meksiko',
                'benefits' => 'Buah segar, sumber lemak sehat',
                'nutritional_value' => 'Lemak, serat, vitamin K',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Markisa',
                'scientific_name' => 'Passiflora edulis',
                'habitat' => 'Brasilia',
                'benefits' => 'Buah segar, bahan baku minuman',
                'nutritional_value' => 'Vitamin C, serat, asam folat',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Anggur',
                'scientific_name' => 'Vitis vinifera',
                'habitat' => 'Eropa dan Asia Barat',
                'benefits' => 'Buah segar, jus, anggur kering',
                'nutritional_value' => 'Vitamin C, vitamin K, resveratrol',
                'pests_and_diseases' => 'Ulat buah, penyakit bulai, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHutanCategory,
                'name' => 'Sengon',
                'scientific_name' => 'Paraserianthes falcataria',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Kayu, bahan bangunan, bahan baku pulp',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kumbang, penyakit busuk kayu, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHutanCategory,
                'name' => 'Jati',
                'scientific_name' => 'Tectona grandis',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Kayu, bahan bangunan, mebel',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kumbang, penyakit busuk kayu, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Mahoni',
                'scientific_name' => 'Swietenia mahagoni',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Kayu berkualitas, tanaman hias',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat kayu, penyakit layu, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Kelor',
                'scientific_name' => 'Moringa oleifera',
                'habitat' => 'Asia Selatan',
                'benefits' => 'Daun sebagai sumber gizi, biji sebagai bahan minyak',
                'nutritional_value' => 'Protein, kalsium, zat besi, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit jamur',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Srikaya',
                'scientific_name' => 'Annona squamosa',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku makanan',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Salak Pondoh',
                'scientific_name' => 'Salacca zalacca',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber serat',
                'nutritional_value' => 'Serat, vitamin C, vitamin A',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Anggrek',
                'scientific_name' => 'Orchidaceae',
                'habitat' => 'Beragam, terutama di daerah tropis',
                'benefits' => 'Tanaman hias, tanaman epifit',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu putih, penyakit bercak daun, penyakit busuk akar',
                'cultivation_techniques' => 'Perbanyakan anak anggrek, pemupukan, penyiraman, pengendalian hama',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Mawar',
                'scientific_name' => 'Rosa',
                'habitat' => 'Asia Barat',
                'benefits' => 'Bunga hias, minyak mawar',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit embun tepung, penyakit bercak hitam',
                'cultivation_techniques' => 'Penanaman stek, pemangkasan, penyiraman, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Krisan',
                'scientific_name' => 'Chrysanthemum',
                'habitat' => 'Asia Timur',
                'benefits' => 'Bunga hias, teh krisan',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit embun tepung, penyakit bercak hitam',
                'cultivation_techniques' => 'Penanaman stek, pemangkasan, penyiraman, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Lavender',
                'scientific_name' => 'Lavandula',
                'habitat' => 'Mediterranea',
                'benefits' => 'Minyak esensial, tanaman hias',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit busuk akar, penyakit cendawan',
                'cultivation_techniques' => 'Penanaman bibit, penyiraman, pemangkasan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Jahe',
                'scientific_name' => 'Zingiber officinale',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Kunyit',
                'scientific_name' => 'Curcuma longa',
                'habitat' => 'Asia Selatan',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, kurkumin',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Temulawak',
                'scientific_name' => 'Curcuma xanthorrhiza',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, kurkumin',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Lengkuas',
                'scientific_name' => 'Alpinia galanga',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, minyak atsiri',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Cengkeh',
                'scientific_name' => 'Syzygium aromaticum',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, minyak cengkeh',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Kenanga',
                'scientific_name' => 'Cananga odorata',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Bunga hias, minyak kenanga',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kelengkeng',
                'scientific_name' => 'Dimocarpus longan',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, serat',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Bambu Wuluh',
                'scientific_name' => 'Bambusa vulgaris',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Material konstruksi, tanaman hias',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit jamur, penyakit bakteri',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Lamtoro',
                'scientific_name' => 'Leucaena leucocephala',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Pakan ternak, pupuk hijau, obat tradisional',
                'nutritional_value' => 'Protein, serat, kalsium',
                'pests_and_diseases' => 'Hama ulat, penyakit layu, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Jarak Pagar',
                'scientific_name' => 'Jatropha curcas',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Bahan baku biodiesel, tanaman pagar hidup',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit layu, penyakit bulai',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Sereh',
                'scientific_name' => 'Cymbopogon citratus',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman bibit, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Sirsak',
                'scientific_name' => 'Annona muricata',
                'habitat' => 'Kepulauan Karibia',
                'benefits' => 'Buah segar, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Kunir',
                'scientific_name' => 'Curcuma longa',
                'habitat' => 'Asia Selatan',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, kurkumin',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Lada',
                'scientific_name' => 'Piper nigrum',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, bumbu masak',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit bercak daun',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kenikir',
                'scientific_name' => 'Cosmos caudatus',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Sayuran, tanaman obat',
                'nutritional_value' => 'Protein, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Bayam',
                'scientific_name' => 'Amaranthus tricolor',
                'habitat' => 'Asia Selatan',
                'benefits' => 'Sayuran, sumber zat besi',
                'nutritional_value' => 'Protein, zat besi, vitamin A',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit layu',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Sawi',
                'scientific_name' => 'Brassica rapa',
                'habitat' => 'Eropa',
                'benefits' => 'Sayuran, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin K, serat',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Pakcoy',
                'scientific_name' => 'Brassica rapa subsp. chinensis',
                'habitat' => 'Asia Timur',
                'benefits' => 'Sayuran, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin K, serat',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Selada',
                'scientific_name' => 'Lactuca sativa',
                'habitat' => 'Eropa',
                'benefits' => 'Sayuran, sumber vitamin K',
                'nutritional_value' => 'Vitamin K, vitamin A, serat',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit layu',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kubis',
                'scientific_name' => 'Brassica oleracea var. capitata',
                'habitat' => 'Eropa',
                'benefits' => 'Sayuran, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin K, serat',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Brokoli',
                'scientific_name' => 'Brassica oleracea var. italica',
                'habitat' => 'Eropa',
                'benefits' => 'Sayuran, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin K, serat',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Kembang Kol',
                'scientific_name' => 'Brassica oleracea var. botrytis',
                'habitat' => 'Eropa',
                'benefits' => 'Tanaman hias, sayuran',
                'nutritional_value' => 'Vitamin C, vitamin K, serat',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Sawo',
                'scientific_name' => 'Manilkara zapota',
                'habitat' => 'Amazone',
                'benefits' => 'Buah segar, bahan baku makanan',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Manggis',
                'scientific_name' => 'Garcinia mangostana',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber antioksidan',
                'nutritional_value' => 'Vitamin C, serat, mineral',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Salak Pondoh',
                'scientific_name' => 'Salacca zalacca',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber serat',
                'nutritional_value' => 'Serat, vitamin C, vitamin A',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Klengkeng',
                'scientific_name' => 'Dimocarpus longan var. malesianus',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, vitamin A, serat',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Matoa',
                'scientific_name' => 'Pometia pinnata',
                'habitat' => 'Melanesia',
                'benefits' => 'Buah segar, sumber vitamin C',
                'nutritional_value' => 'Vitamin C, serat, mineral',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Mangga Gedong',
                'scientific_name' => 'Mangifera indica',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku makanan',
                'nutritional_value' => 'Vitamin C, vitamin A, serat',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Sirsak',
                'scientific_name' => 'Annona muricata',
                'habitat' => 'Kepulauan Karibia',
                'benefits' => 'Buah segar, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Nangka',
                'scientific_name' => 'Artocarpus heterophyllus',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku masakan',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Ulat buah, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Delima',
                'scientific_name' => 'Punica granatum',
                'habitat' => 'Asia Barat',
                'benefits' => 'Buah segar, sumber antioksidan',
                'nutritional_value' => 'Vitamin C, vitamin K, serat',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Pare',
                'scientific_name' => 'Momordica charantia',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Sayuran, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit embun tepung, penyakit layu',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Bambu',
                'scientific_name' => 'Bambusoideae',
                'habitat' => 'Berbagai belahan dunia',
                'benefits' => 'Material konstruksi, tanaman hias',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit jamur, penyakit bakteri',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Kamboja',
                'scientific_name' => 'Plumeria',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Bunga hias, tanaman obat',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Markisa',
                'scientific_name' => 'Passiflora edulis',
                'habitat' => 'Amerika Selatan',
                'benefits' => 'Buah segar, bahan baku minuman',
                'nutritional_value' => 'Vitamin C, serat, mineral',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Pala',
                'scientific_name' => 'Myristica fragrans',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, bumbu masak',
                'nutritional_value' => 'Karbohidrat, serat, mineral',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Terong Belanda',
                'scientific_name' => 'Solanum betaceum',
                'habitat' => 'Andes, Amerika Selatan',
                'benefits' => 'Buah segar, bahan baku masakan',
                'nutritional_value' => 'Vitamin C, serat, mineral',
                'pests_and_diseases' => 'Ulat buah, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Balung',
                'scientific_name' => 'Ixora coccinea',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Tanaman hias, tanaman pagar',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit bakteri, penyakit jamur',
                'cultivation_techniques' => 'Penanaman stek, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Kecubung',
                'scientific_name' => 'Catharanthus roseus',
                'habitat' => 'Madagaskar',
                'benefits' => 'Tanaman hias, tanaman obat',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit jamur, penyakit bakteri',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Sirih',
                'scientific_name' => 'Piper betle',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Tanaman obat, tradisi kesehatan',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman stek, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Kencur',
                'scientific_name' => 'Kaempferia galanga',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, minyak atsiri',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kecombrang',
                'scientific_name' => 'Etlingera elatior',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Sayuran, bumbu masak',
                'nutritional_value' => 'Vitamin C, serat, mineral',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit layu',
                'cultivation_techniques' => 'Penanaman rumpun, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Kumis Kucing',
                'scientific_name' => 'Orthosiphon aristatus',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Herbal, obat tradisional',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kluwak',
                'scientific_name' => 'Pangium edule',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Bahan baku masakan, sambal kluwak',
                'nutritional_value' => 'Karbohidrat, protein, lemak',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Kapulaga',
                'scientific_name' => 'Elettaria cardamomum',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, bumbu masak',
                'nutritional_value' => 'Karbohidrat, serat, minyak atsiri',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk buah, penyakit antraknosa',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanHiasCategory,
                'name' => 'Serei',
                'scientific_name' => 'Citronella winterianus',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Tanaman hias, bahan baku minyak serai',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama kutu daun, penyakit antraknosa, penyakit jamur',
                'cultivation_techniques' => 'Penanaman stek, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Srikaya',
                'scientific_name' => 'Annona squamosa',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku minuman',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Blewah',
                'scientific_name' => 'Benincasa hispida',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku minuman',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Kunir Putih',
                'scientific_name' => 'Curcuma zedoaria',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Rempah-rempah, obat tradisional',
                'nutritional_value' => 'Karbohidrat, serat, minyak atsiri',
                'pests_and_diseases' => 'Hama ulat, penyakit busuk akar, penyakit jamur',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Petai',
                'scientific_name' => 'Parkia speciosa',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku masakan',
                'nutritional_value' => 'Protein, karbohidrat, serat',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Binahong',
                'scientific_name' => 'Anredera cordifolia',
                'habitat' => 'Amerika Tengah',
                'benefits' => 'Herbal, obat tradisional',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit jamur',
                'cultivation_techniques' => 'Penanaman stek, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Manggis',
                'scientific_name' => 'Garcinia mangostana',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, sumber antioksidan',
                'nutritional_value' => 'Vitamin C, serat, mineral',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanPanganCategory,
                'name' => 'Serut',
                'scientific_name' => 'Flacourtia inermis',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Buah segar, bahan baku minuman',
                'nutritional_value' => 'Karbohidrat, serat, vitamin C',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit busuk buah',
                'cultivation_techniques' => 'Penanaman biji, pemangkasan, pengairan, pemupukan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Sambiloto',
                'scientific_name' => 'Andrographis paniculata',
                'habitat' => 'Asia Tenggara',
                'benefits' => 'Herbal, obat tradisional',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit jamur',
                'cultivation_techniques' => 'Penanaman biji, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'plant_category_id' => $tanamanObatCategory,
                'name' => 'Akar Wangi',
                'scientific_name' => 'Vetiveria zizanioides',
                'habitat' => 'Asia Selatan',
                'benefits' => 'Minyak wangi, tanaman pengikat tanah',
                'nutritional_value' => 'Tidak berlaku (tidak dimakan)',
                'pests_and_diseases' => 'Hama ulat, penyakit antraknosa, penyakit busuk akar',
                'cultivation_techniques' => 'Penanaman rimpang, pemupukan, pengairan, pemangkasan',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Plant::insert($plants);
    }
}
